"""
Phase 0 itinerary planner.

Filtering is plain Python (deterministic, auditable — this is the allergen
safety net, not an LLM). Only the final narrative write-up is generated by
an LLM, grounded strictly in the dishes the filter already approved.

Pipeline, in order (see server.py / cli.py for where each is called):
    load_dishes -> filter_dishes -> [rank_candidates_by_preference, optional,
    lives in embedding/query.py] -> build_daily_plan -> generate_narrative
    (or generate_narrative_rag if a preference was given).
"""

import csv
import os
import random

# Which model writes the narrative. Cheap/fast model is used for enrichment
# (enrichment/enrich.py) instead -- this one is user-facing prose, so it uses
# the better model.
MODEL = os.environ.get("PLANNER_MODEL", "anthropic/claude-sonnet-5")

COURSE_SLOTS = ["main dish", "salad", "snack", "dessert"]


def load_dishes(path):
    """Read the enriched dish CSV into a list of plain dicts -- every other
    function in this module just operates on that list, no DB/ORM involved."""
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def dish_allergens(dish):
    # allergens are stored as a single "+"-joined string in the CSV (e.g.
    # "fish+crustacean_shellfish") because CSV doesn't have a native list
    # type -- split back into a set here for fast membership/intersection
    # checks. The `if a` guards against an empty string producing a bogus
    # {''} set when a dish has no allergens at all.
    return set(a for a in dish.get("allergens", "").split("+") if a)


def dish_dietary_tags(dish):
    return set(t for t in dish.get("dietary_tags", "").split("+") if t)


def filter_dishes(dishes, regions=None, exclude_allergens=None, max_spice=5, required_diet=None):
    """The safety-critical step: everything here is deterministic set/int
    comparison, not a model guess, because this is what actually has to be
    correct for allergen/diet safety -- see DATA_SOURCES.md for why this is
    kept separate from anything the LLM touches."""
    exclude_allergens = set(exclude_allergens or [])
    out = []
    for d in dishes:
        if regions and d["region"] not in regions:
            continue
        # a dish is excluded if ANY of its allergens is in the exclusion
        # set -- set intersection is just the concise way to express that
        if dish_allergens(d) & exclude_allergens:
            continue
        try:
            if int(d.get("spice_level", 5)) > max_spice:
                continue
        except ValueError:
            # malformed/missing spice_level -- treat as "can't confirm this
            # is within the traveler's limit" and exclude it, rather than
            # assume it's safe. Same fail-closed philosophy as allergens.
            continue
        if required_diet and required_diet != "none" and required_diet not in dish_dietary_tags(d):
            continue
        out.append(d)
    return out


def build_daily_plan(filtered, days, shuffle=True):
    """Split the (already safety-filtered) dish list into `days` groups of
    up to 3 meals each.

    shuffle=True (default): randomize dish order first -- used when there's
    no relevance ranking to respect (the plain, non-RAG path).
    shuffle=False: keep the given order -- used for the RAG path, where
    `filtered` has already been sorted best-first by embedding similarity to
    the traveler's stated preference (see server.py's /api/itinerary), and
    that relevance order needs to survive into which dishes land on which day.

    Implementation note: this used to track a separate `used` set and a
    monotonically increasing index to avoid repeating a dish across days.
    That had a real bug -- confirmed by testing, not just suspected: with a
    pool of exactly 3 dishes and 3 days requested, day 2 came back as an
    empty list. Root cause was that the index-wrapping logic could only
    "break out" of filling a day at the exact moment it wrapped, which
    sometimes happened before any dish had been assigned to that day at all.
    Cycling through the (possibly shuffled) pool with modulo indexing avoids
    that class of bug entirely: every day always gets `meals_per_day` dishes,
    guaranteed, and dishes only repeat once every dish in the pool has
    already appeared once.
    """
    if not filtered:
        return []

    pool = filtered[:]
    if shuffle:
        random.shuffle(pool)

    # Don't force 3 repeats of the SAME dish within one day just because the
    # pool is small (e.g. only 1 dish passes a strict vegan+region filter) --
    # show fewer meals that day instead. Cross-day repeats are still fine;
    # same-day repeats of one dish read oddly in the generated narrative.
    meals_per_day = min(3, len(pool))
    total_slots = days * meals_per_day
    selected = [pool[i % len(pool)] for i in range(total_slots)]

    plan = []
    for day in range(1, days + 1):
        start = (day - 1) * meals_per_day
        plan.append({"day": day, "dishes": selected[start : start + meals_per_day]})
    return plan


def _usage_dict(completion):
    """Pulls token counts off the raw API response so callers that care
    about cost (e.g. testing/run_eval.py) don't have to reach into SDK
    internals themselves. Returns None if the provider didn't send usage
    data back for some reason, rather than crashing."""
    usage = getattr(completion, "usage", None)
    if usage is None:
        return None
    return {
        "prompt_tokens": usage.prompt_tokens,
        "completion_tokens": usage.completion_tokens,
        "total_tokens": usage.total_tokens,
    }


def generate_narrative(client, plan, preferences):
    """Returns (narrative_text, usage_dict) -- see _usage_dict above."""
    lines = []
    for entry in plan:
        for d in entry["dishes"]:
            lines.append(
                f"Day {entry['day']} | {d['en_name']} ({d['th_name']}) | "
                f"{d['province']}, {d['region']} | ingredients: {d['ingredients']} | "
                f"spice: {d.get('spice_level', '?')}/5 | flavor: {d.get('flavor_profile', '?')}"
            )
    grounding = "\n".join(lines)

    prompt = f"""You are a Thai food travel guide. Write a short, friendly day-by-day
food itinerary using ONLY the dishes listed below — do not invent dishes,
ingredients, or restaurants that are not in this list.

Traveler preferences: {preferences}

Approved dishes for this trip (already filtered for allergens/spice/diet):
{grounding}

For each day, write 2-4 sentences per dish: what it is, why it fits the
province/region, and one thing to notice about it (flavor, texture, how it's
eaten). Do not claim any specific restaurant, vendor, or price — this version
of the guide only covers what to seek out, not where."""

    completion = client.chat.completions.create(
        model=MODEL,
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    return completion.choices[0].message.content, _usage_dict(completion)


def generate_narrative_rag(client, plan, preferences, preference_text, retrieval_scores):
    """RAG version of generate_narrative.

    The difference from the plain version isn't the LLM call mechanics --
    it's that the prompt makes BOTH retrieval steps explicit instead of just
    saying "approved dishes": (1) the deterministic hard filter (safety --
    allergens/diet/region/spice) and (2) the embedding similarity ranking
    against the traveler's own words. Giving the model the actual similarity
    scores lets it be honest when the "best available" match is still weak,
    instead of writing as if every dish were a perfect fit for the craving.

    retrieval_scores: {en_name: cosine_similarity_score} from
    embedding/query.py's rank_candidates_by_preference -- this IS the output
    of the retrieval model the prompt below refers to.
    """
    lines = []
    for entry in plan:
        for d in entry["dishes"]:
            score = retrieval_scores.get(d["en_name"])
            score_str = f"{score:.2f}" if score is not None else "n/a"
            lines.append(
                f"Day {entry['day']} | {d['en_name']} ({d['th_name']}) | "
                f"{d['province']}, {d['region']} | ingredients: {d['ingredients']} | "
                f"spice: {d.get('spice_level', '?')}/5 | flavor: {d.get('flavor_profile', '?')} | "
                f"craving-match score: {score_str} (cosine similarity, 1.0 = perfect match)"
            )
    retrieved_context = "\n".join(lines)

    prompt = f"""You are a Thai food travel guide. You do NOT have general knowledge of
Thai cuisine to draw on here -- everything you know about this trip comes
from the RETRIEVED DISHES listed below. Do not invent dishes, ingredients, or
restaurants that are not in that list, and do not claim a specific
restaurant, vendor, or price.

How these dishes were retrieved (two stages, already run before you were
called):
1. Hard filter (safety-critical, deterministic -- not your job to re-check):
   every dish below has already been confirmed to respect the traveler's
   allergy exclusions, diet requirement, region choice, and spice limit.
2. Preference ranking (this is the retrieval model's output): the traveler
   described what they're craving in their own words below. An embedding
   similarity search compared that description against every dish that
   survived step 1, and ranked them. The "craving-match score" on each line
   is that result.

Traveler's stated craving: "{preference_text}"
Traveler's hard constraints: {preferences}

Retrieved dishes (safety-filtered, ordered by craving-match score):
{retrieved_context}

Write a short, friendly day-by-day itinerary using ONLY the dishes above, in
roughly the order given (the best craving matches first). For each dish,
write 2-4 sentences: what it is, why it fits the province/region, and one
thing to notice about it. If a dish's craving-match score is low, say so
honestly -- e.g. "this isn't a close match for what you described, but it's
one of the few options left once we filtered for your allergies" -- rather
than pretending every dish is an ideal fit."""

    completion = client.chat.completions.create(
        model=MODEL,
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    return completion.choices[0].message.content, _usage_dict(completion)
