"""
Phase 0 itinerary planner.

Filtering is plain Python (deterministic, auditable — this is the allergen
safety net, not an LLM). Only the final narrative write-up is generated by
an LLM, grounded strictly in the dishes the filter already approved.
"""

import csv
import os
import random

import anthropic

MODEL = os.environ.get("PLANNER_MODEL", "claude-sonnet-5")

COURSE_SLOTS = ["main dish", "salad", "snack", "dessert"]


def load_dishes(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def dish_allergens(dish):
    return set(a for a in dish.get("allergens", "").split("+") if a)


def dish_dietary_tags(dish):
    return set(t for t in dish.get("dietary_tags", "").split("+") if t)


def filter_dishes(dishes, regions=None, exclude_allergens=None, max_spice=5, required_diet=None):
    exclude_allergens = set(exclude_allergens or [])
    out = []
    for d in dishes:
        if regions and d["region"] not in regions:
            continue
        if dish_allergens(d) & exclude_allergens:
            continue
        try:
            if int(d.get("spice_level", 5)) > max_spice:
                continue
        except ValueError:
            continue
        if required_diet and required_diet != "none" and required_diet not in dish_dietary_tags(d):
            continue
        out.append(d)
    return out


def build_daily_plan(filtered, days):
    """Pick up to 3 meals/day from filtered dishes, avoiding repeats, cycling
    through provinces so the plan reads as an actual regional route."""
    if not filtered:
        return []

    pool = filtered[:]
    random.shuffle(pool)
    plan = []
    used = set()
    idx = 0
    for day in range(1, days + 1):
        day_dishes = []
        for _ in range(3):
            if idx >= len(pool):
                idx = 0
                if not any(d["en_name"] not in used for d in pool):
                    break
            candidate = pool[idx]
            idx += 1
            if candidate["en_name"] in used and len(used) < len(pool):
                continue
            used.add(candidate["en_name"])
            day_dishes.append(candidate)
        plan.append({"day": day, "dishes": day_dishes})
    return plan


def generate_narrative(client, plan, preferences):
    lines = []
    for entry in plan:
        for d in entry["dishes"]:
            lines.append(
                f"Day {entry['day']} | {d['en_name']} ({d['th_name']}) | "
                f"{d['province']}, {d['region']} | ingredients: {d['ingredients']} | "
                f"spice: {d.get('spice_level', '?')}/5 | flavor: {d.get('flavor_profile', '?')}"
            )
    grounding = "\n".join(lines)

    prompt = f"""You are a Thai food travel guide. Write a short, friendly day-by-day
food itinerary using ONLY the dishes listed below — do not invent dishes,
ingredients, or restaurants that are not in this list.

Traveler preferences: {preferences}

Approved dishes for this trip (already filtered for allergens/spice/diet):
{grounding}

For each day, write 2-4 sentences per dish: what it is, why it fits the
province/region, and one thing to notice about it (flavor, texture, how it's
eaten). Do not claim any specific restaurant, vendor, or price — this version
of the guide only covers what to seek out, not where."""

    message = client.messages.create(
        model=MODEL,
        max_tokens=2048,
        messages=[{"role": "user", "content": prompt}],
    )
    return "".join(b.text for b in message.content if b.type == "text")
